# Generated by Django 3.2.2 on 2021-05-11 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='titel',
            new_name='title',
        ),
    ]
